### PR TITLE
bump to real adapter

### LINKED ISSUE #23: navigator.mozGetUserMedia replaced by navigator.mediaDevices.getUserMedia
navigator.mozGetUserMedia replaced by navigator.mediaDevices.getUserMedia

### PR DESCRIPTION
**Pull request by fippo**
fixes #23 along the way (which i think is just an issue in the bundle)

see also https://github.com/otalk/RTCPeerConnection/pull/63 and https://github.com/otalk/traceablepeerconnection/pull/7

### CODE REVIEW

**Comment by tgabi333** [comment]
`adapter.webrtcDetectedBrowser` was replaced by `adapter.browserDetails.browser`

**Comment by tgabi333** [comment]
`adapter.webrtcDetectedBrowser` was replaced by `adapter.browserDetails.browser`

**Comment by tgabi333** [comment]
@fippo Could you please release it?

**Comment by fippo** [comment]
published as 1.3.6, thanks!

**Pull request merged**
