### PR TITLE
remove fake flag, use about:config instead

### PR DESCRIPTION
**Pull request by fippo**
technically that is a breaking change...

### CODE REVIEW

**Comment by xdumaine** [comment]
Do you know if the about:config flag can be automated?

**Comment by fippo** [comment]
yes, see https://github.com/webrtc/utilities/blob/master/src/selenium/selenium-lib.js#L55

**Comment by tgabi333** [comment]
@fippo Could you please release it?

**Comment by fippo** [comment]
done. thanks for resolving my dilemma of whether this should be a major version or not :-)

**Pull request merged**
